### ISSUE TITLE
可以隐藏控制栏目？

### ISSUE THREAD

**Issue by wengAlan** [dblate/larkplayer#3]
👏 欢迎提出 bug 或者新的想法
可以隐藏控制栏目？

**Comment by dblate** [comment]
目前是在交互过程中自动显示或隐藏控制条（demo 页：https://s.codepen.io/dblate/debug/vRybLW/XBAGRoLZBbZr）
是有 js 手动控制 控制条 显隐的需求吗？

**Comment by wengAlan** [comment]
有这需求，我这边做贴片广告，在移动端的，你有研究过如何更好的兼容安卓设备么

**Comment by wengAlan** [comment]
大神能给个联系方式，多跟你学习？

**Comment by dblate** [comment]
不是大神哈，可以通过 173983476@qq.com 这个邮箱联系我，我每隔几天会看一下。不过播放器相关的问题可能还在 github 上提 issue 好点，我现在每天都会关注。

另外我打算添加两个功能：
1. 增加 controls 和 nativeControls 两个参数，用于控制自定义 UI 控制条 和 原生控制条的显隐
2. 增加各 UI 组件的 disable 功能，考虑到实用性，先增加 progressBar 的 disbale 和 enable 功能

我理解贴片广告应该是一段单独的视频是吧？
这种情况播广告时隐藏控制条并不是一个很好的选择，我们应该可以允许用户进行暂停、全屏等操作，不过不能进行拖动进度条这类的操作。
但是考虑到移动端浏览器播放视频的限制（经常被浏览器各种代理播放器），可能隐藏控制条也算是一个保底的操作吧～

我尽量在下周末之前陆续完成这两个功能

**Comment by dblate** [comment]
另外播放器可能会在设计方面做一些调整，后续我会贴出更详细的文档。
对使用者不会有大的影响，但是可能需要有一些小改动

**Comment by wengAlan** [comment]
两部视频如何无缝播放，在移动端上实现，我之前看了爱奇艺的播放器能实现无缝播放

**Comment by dblate** [comment]
player.on('ended', function () {
    player.src('xxx.mp4');
    player.play();
});

快速上手里有这个代码

**Comment by wengAlan** [comment]
这样播放会有卡顿的

**Comment by dblate** [comment]
我看了下爱奇艺的 web 版广告，是打在视频里的，所以就顺着无缝播放了（是用云服务把广告和正片合成了一个视频）

**Comment by dblate** [comment]
增加了 controls 方法，player.controls(true/false) 控制控制条显隐藏，你更新下代码吧！
https://github.com/dblate/larkplayer/blob/master/docs/player.md#Player+controls

原生控制条的处理以及 disable 功能还没想好，所以还没添加

**Comment by wengAlan** [comment]
爱奇艺的wap版我看了是多个视频的，不是合成的

**Comment by dblate** [comment]
我判断视频是合成的方法是：
我是 ios 手机，将视频全屏，就能看到视频总时长是广告加正片长度。然后拉动进度条保持不放，能看到正片内容。
我不太清楚你怎么判断的

**Comment by wengAlan** [comment]
![image](https://user-images.githubusercontent.com/20350202/38599321-9899a960-3d92-11e8-821c-ec56edda91c1.png)我直接看url

**Comment by wengAlan** [comment]
如果是合并的不可能是多条链接吧
