### ISSUE TITLE
当点击播放视频时，我这边如何判断视频完全加载完

### ISSUE THREAD

**Issue by wengAlan** [dblate/larkplayer#4]
👏 欢迎提出 bug 或者新的想法
![image](https://user-images.githubusercontent.com/20350202/38604288-7049f5b8-3da2-11e8-9029-5412104dbeb2.png)
当点击播放视频时，我这边如何判断视频完全加载完，若视频还未加载完就显示loading，视频加载完了才开始播放

**Comment by dblate** [comment]
是想要显示自己的 loading 样式吗？
可以参考 canplay 和 canplaythrough 这两个事件

**Comment by wengAlan** [comment]
对了，我这边出了一个问题
我这边在在家app内打开网页播放，然后点击全屏视频，后面点关闭全屏按钮显示空白页

**Comment by wengAlan** [comment]
![image](https://user-images.githubusercontent.com/20350202/38716277-659a3044-3f12-11e8-9430-9fda1dc3e0db.png)
这里的总时间是可以设置参数的？？？

**Comment by dblate** [comment]
1. app 那种情况我没法帮你分析，有可能是其他代码的问题
2. duration 现在确实可以设置参数，但实际是没用的，后续我会把它去掉并在文档中标识
3. 一个 issue 处理一个问题，有其他疑问请另开 issue
