### ISSUE TITLE
duration 设置参数

### ISSUE THREAD

**Issue by wengAlan** [dblate/larkplayer#6]
文档么看到duration 设置参数，好像都直接去获取视频长度来显示的

**Comment by dblate** [comment]
1. duration 方法不能设置参数，[w3c 规范](https://www.w3.org/TR/html5/semantics-embedded-content.html#dom-htmlmediaelement-duration) 里 duration 是只读的
2. [issue 4](https://github.com/dblate/larkplayer/issues/4) 里我说错了，当时我以为我给 duratiojn 方法加了参数，但现在看了下并没有
